server:
  port: 8888
  servlet:
    context-path: /food-menu
wx:
  appId: wx943dee8b7e3224fd
  secretId: 80ac34369b3f65ac87df55f95730eda1
spring:
  redis:
    host: 192.168.174.129
    port: 6379
    database: 0
    password: itzixi
    timeout: 5000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/food_menu?useSSL=true&serverTimezone=UTC
mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: vip.huhailong.foodmenu.entity
  mapper-locations: classpath:mapper/*.xml